pool:
  vmImage: 'ubuntu-latest'  # Adjust VM image if needed

stages:
- stage: Build
  jobs:
  - job: Build_Job
    steps:
    - task: Maven@3  # Use the appropriate Maven version task
      inputs:
        mavenVersion: '3.x'  # Specify your Maven version
        mavenPomFile: 'pom.xml'  # Path to your pom.xml file
        goals: 'clean package'  # Maven goals to execute (clean and package)
        publishMavenArtifacts: true  # Optionally publish artifacts

- stage: Test
  jobs:
  - job: Test_Job
    steps:
    - task: Maven@3  # Use the same Maven task for running tests
      inputs:
        mavenVersion: '3.x'  # Specify your Maven version
        mavenPomFile: 'pom.xml'  # Path to your pom.xml file
        goals: 'test -P regression'  # Maven goals to execute tests
        publishJUnitResults: true  # Publish JUnit test results
        testResultsFiles: '**/target/surefire-reports/*.xml'  # Path to test results

